#!/bin/sh
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/acl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/at.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/attr.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/bash.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/bc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/busybox.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/bzip2.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/coreutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/cpio.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/cracklib.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/cronie.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/diffutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/e2fsprogs.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/ed.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/ethtool.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/file.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/findutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/gawk.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/grep.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/gzip.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/initscripts.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/iproute.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/iptables.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/iputils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/kmod.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/less.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/util-linux.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/time.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/tar.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/sudo.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/shadow.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/sed.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/rpcbind.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/rng-tools.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/psmisc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/procps-ng.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/perl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/patch.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/openssl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/openssh.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/nfs-utils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/net-tools.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/ncurses.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/shared-mime-info.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/procps-ng.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/mc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/make.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/m4.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/logrotate.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/zlib.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libxml2.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/findutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/elfutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libcap.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libcap-ng.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libffi.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libgcrypt.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/glibc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/gcc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libidn2.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libtasn1.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/gnutls.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libunistring.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/lz4.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/nettle.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/popt.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/perl-libxml-perl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/xz.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/gmp.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/glib2.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libgpg-error.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/pcre2.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libmnl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/readline.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/sysfsutils.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libtirpc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/audit.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/clibcni.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/curl.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/http-parser.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/iSulad.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libarchive.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libevent.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libevhtp.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libpwquality.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/libseccomp.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/lxc.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/pam.git
  git clone -b openEuler-21.09 https://gitee.com/src-openeuler/dpkg.git
  
